services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: law_rag_chatbot
        ports:
            - "5000:5000"
        env_file:
            - .env
        volumes:
            - ./main.py:/app/main.py
            - ./rag_components.py:/app/rag_components.py
            - ./build_vectorstore.py:/app/build_vectorstore.py
            - ./config.py:/app/config.py
            - ./prompt_templete.py:/app/prompt_templete.py
            - ./custom_output_parser.py:/app/custom_output_parser.py
            - ./dependencies.py:/app/dependencies.py
            - ./time_priority_retriever.py:/app/time_priority_retriever.py
            - ./data:/app/data
            - ./utils:/app/utils
            - ./vector_store:/app/vector_store
            - ./db:/app/db
            - ./routers:/app/routers
            - ./schemas:/app/schemas
            - ./services:/app/services
            - hf_cache:/app/cache
        environment:
            - TRANSFORMERS_CACHE=/app/cache
            - HF_HOME=/app/cache
            - HF_HUB_DISABLE_SYMLINKS_WARNING=1
        restart: unless-stopped
        depends_on:
            - redis

    redis:
        image: redis:7.2-alpine
        container_name: redis-chatbot
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        restart: always

volumes:
    redis_data:
    hf_cache:
