services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: law_rag_chatbot
        ports:
            - "5000:5000"
        env_file:
            - .env
        volumes:
            - ./main.py:/app/main.py
            - ./rag_components.py:/app/rag_components.py
            - ./build_vectorstore.py:/app/build_vectorstore.py
            - ./config.py:/app/config.py
            - ./prompt_templete.py:/app/prompt_templete.py
            - ./dependencies.py:/app/dependencies.py
            - ./data:/app/data
            - ./utils:/app/utils
            - ./db:/app/db
            - ./routers:/app/routers
            - ./schemas:/app/schemas
            - ./services:/app/services
            - ./core:/app/core
            - hf_cache:/app/cache
        environment:
            - HF_HOME=/app/cache
            - HF_HUB_DISABLE_SYMLINKS_WARNING=1
            # - WEAVIATE_URL=http://weaviate:8080
        restart: unless-stopped
        # depends_on:
        # - weaviate
        networks:
            - law-network

    # weaviate:
    #     image: cr.weaviate.io/semitechnologies/weaviate:1.30.2
    #     container_name: weaviate-law
    #     ports:
    #         - "8080:8080"
    #         - "50051:50051"
    #     volumes:
    #         - weaviate_data:/var/lib/weaviate
    #     restart: on-failure:0
    #     environment:
    #         QUERY_DEFAULTS_LIMIT: 25
    #         AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
    #         PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
    #         ENABLE_API_BASED_MODULES: "true"
    #         CLUSTER_HOSTNAME: "node1"
    #         DEFAULT_VECTORIZER_MODULE: "none"
    #     networks:
    #         - law-network

volumes:
    # redis_data:
    hf_cache:
    # weaviate_data:

networks:
    law-network:
        driver: bridge
